version: '3.1'


services:
  apache:
    image: php:7.2-apache
    container_name: php_apache
    restart: always
    ports:
      - '8080:80'
    volumes:
      - /opt/apache2:/var/www/html


  db:
    image: mysql:5.7
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_DATABASE: tp3_db
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - '3306:3306'
  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db


